### ISSUE TITLE
`tf.data.Dataset` warpper

### ISSUE THREAD

**Issue by sayakpaul** [soumik12345/point-cloud-segmentation#2]
While we are at it I thought of building on top of your work and create `tf.data.Dataset` objects: https://colab.research.google.com/gist/sayakpaul/67c5c725faff48a5f26c7e2cbbabce06/scratchpad.ipynb. Need a bit of verification. 

@soumik12345

**Comment by soumik12345** [comment]
Refer to https://github.com/soumik12345/point-cloud-segmentation/pull/3
