### ISSUE TITLE
name 'TransformerEncoder' is not defined

### ISSUE THREAD

**Issue by MrSquidward** [soumik12345/point-cloud-segmentation#35]
I have adopted your work to my distributed environment using HDFS and Horovod, but I am getting the error name 'TransformerEncoder' is not defined, which relates to the `OrthogonalRegularizer` class and line `config = super(TransformerEncoder, self).get_config()` in the `get_config` function. Obviously, as you can check, the name TransformerEncoder is nowhere to be found in your work. What should be the value of this object or from where should I import this class?

I appreciate your work, and I find this example very useful. Thank you in advance for your help.

**Comment by sayakpaul** [comment]
Could you please provide a link to the line that has `TransformerEncoder`?

**Comment by MrSquidward** [comment]
I just found out I was using an outdated version of your model. You have fixed that issue in one of the commits. I just had to upgrade my model to the latest version. If you have access to the [keras.io example](https://keras.io/examples/vision/pointnet_segmentation/) you should consider updating that code too.

Thanks for the replay and keep up the great work!

**Comment by sayakpaul** [comment]
Thanks!

@soumik12345 could you update the example? It's in the `OrthogonalRegularizer` layer. 

```
class OrthogonalRegularizer(keras.regularizers.Regularizer):
    """Reference: https://keras.io/examples/vision/pointnet/#build-a-model"""

    def __init__(self, num_features, l2reg=0.001):
        self.num_features = num_features
        self.l2reg = l2reg
        self.identity = tf.eye(num_features)

    def __call__(self, x):
        x = tf.reshape(x, (-1, self.num_features, self.num_features))
        xxt = tf.tensordot(x, x, axes=(2, 2))
        xxt = tf.reshape(xxt, (-1, self.num_features, self.num_features))
        return tf.reduce_sum(self.l2reg * tf.square(xxt - self.identity))

    def get_config(self):
        config = super(TransformerEncoder, self).get_config()
        config.update({"num_features": self.num_features, "l2reg_strength": self.l2reg})
        return config
```
