### ISSUE TITLE
can not segmentation_model.save('my_model.h5')  

### ISSUE THREAD

**Issue by wr0124** [soumik12345/point-cloud-segmentation#38]
Hi, it is so great that you share your work!  but when I try to save the complete model after trainning by command: segmentation_model.save('my_model.h5')  , it shows up :  NotImplementedError: <__main__.OrthogonalRegularizer object at 0x7f5284ca5040> does not implement get_config() ,  it seems that line : config = super().get_config()  cased this problem?  Can you help on this ?  Thanks !

**Comment by soumik12345** [comment]
Please use TensorFlow savedmodel format.
https://www.tensorflow.org/guide/saved_model
